### ISSUE TITLE
Incorrect status for newly created files

### ISSUE THREAD

**Issue by artagnon** [alefragnani/atom-read-only-indicator#3]
Why does it say [RO] for a file I've just opened?

**Comment by alefragnani** [comment]
Is it happening _every time_ you do this? Is there something special with the folder, like:
- Read Only
- User without permission
- Network Shared

In which OS are you having this problem?

**Comment by artagnon** [comment]
Yes, it's happening _every_ time. The folder network mounted, but that shouldn't matter in principle. I'm on OS X.

Thanks.

**Comment by alefragnani** [comment]
This problem seems to be on macOS only, and unfortunately I don't have a Mac available for a long time.
I'm adding _help wanted_ label in case someone with a Mac could fix it and make a PR.

**Comment by alefragnani** [comment]
I'm closing this issue because it didn’t receive enough upvotes from the community, neither a PR has been provided.

Thanks for your understanding
