### ISSUE TITLE
Click on StatusBar to change File Access

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/atom-read-only-indicator#7]
Allow to change the File Access also clicking in the StatusBar item (today it only works as commands in Command Palette).

Just like I did in VSCode

**Comment by zarathosss** [comment]
This enhancement will be really useful, looking forward your implementation about it ;)

**Comment by jmtoniolo** [comment]
Can you maybe point me in the right direction on this? In the flight manual or online I can't find much on handling click events. I see that fs supports changing file attributes so we could change the write permissions presumably but making it support click in the status bar is a bit tricky.
